// Migration: delegation token-usage provenance
// Created: 2026-07-27
//
// DOWN: reversible
//
// Distinguishes provider-reported usage from local estimates so calibration
// never learns from values generated by the estimator itself.

import type { Db } from '../types.js';

function hasColumn(db: Db): boolean {
  const columns = db.prepare('PRAGMA table_info(delegation_history)').all() as { name: string }[];
  return columns.some(candidate => candidate.name === 'usage_estimated');
}

export function up(db: Db): void {
  if (!hasColumn(db)) {
    db.prepare(`
      ALTER TABLE delegation_history
      ADD COLUMN usage_estimated INTEGER
      CHECK (usage_estimated IN (0, 1))
    `).run();
  }
}

export function down(db: Db): void {
  if (hasColumn(db)) {
    db.prepare('ALTER TABLE delegation_history DROP COLUMN usage_estimated').run();
  }
}
